name: Daily Scam Scraper

on:
  schedule:
    - cron: "0 3 * * *"  # Runs daily at 03:00 UTC
  workflow_dispatch:     # Allows manual run from GitHub UI

jobs:
  scrape:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Reddit scraper
        run: python scrapers/reddit.py

      - name: Run Trustpilot scraper
        run: python scrapers/trustpilot.py

      - name: Run ScamAdviser scraper
        run: python scrapers/scamadvisor.py

      - name: Run ActionFraud scraper
        run: python scrapers/actionfraud.py
